### ISSUE TITLE
Error: module compiled with Swift 4.0 cannot be imported in Swift 4.0.3 - SourceryRuntime

### ISSUE THREAD

**Issue by pgorzelany** [MakeAWishFoundation/SwiftyMocky#103]
Hi guys,

First of all thanks for all the hard work you've put into this project, it looks great. I wanted to try out SwiftMocky in one of our projects and hit an error right away at the mock generation phase.

I am using Xcode 9.2, Swift 4.0.3. I installed SwiftMocky (1.0.2) through Cocoapods (1.3.1) configured the mocky.yml file as instructed in the docs and run :

`Pods/Sourcery/bin/Sourcery.app/Contents/MacOS/Sourcery --config mocky.yml`

I get the following output
```
Using configuration file at 'mocky.yml'
Scanning sources...
Found 582 types.
Loading templates...
Loaded 1 templates.
Generating code...
error: /var/folders/s2/xq1bmrbn2y9grg4m2_lppplr0000gq/T/Sourcery.build/main.swift:2:8: error: module compiled with Swift 4.0 cannot be imported in Swift 4.0.3: /var/folders/s2/xq1bmrbn2y9grg4m2_lppplr0000gq/T/SourceryRuntime.framework/Modules/SourceryRuntime.swiftmodule/x86_64.swiftmodule
import SourceryRuntime
```
I suspect that the SourceryRuntime lib is precompiled using a different version of Swift. Do you have a workaround to this issue?

**Comment by Przemyslaw-Wosko** [comment]
@pgorzelany Thanks for reaching out, we will investigate this isssue. 
I haven't checked Xcode 9.2 yet, i'm still working on 9.1. We described installation process under this page: 
https://cdn.rawgit.com/MakeAWishFoundation/SwiftyMocky/f9a57ad0/docs/installation.html

Steps you can try out: 
1) Make sure you have selected command line tools the same as xcode version you are using for project
2) try to update Sourcery pod - check out your Podfile.lock - make sure you have new version of Sourcery installed.
3) eventually add post install script to your Podfile to get other binary of sourcery, then change paths in `mocky.yml`
```
post_install do |installer|
    system("sh Pods/SwiftyMocky/get_sourcery.sh 4.0.2")
end
```
Version 4.0.2 and 4.0.3 shoud be compatibile, but if not, we will add new sourcery binary, built with 4.0.3.

**Comment by pgorzelany** [comment]
@Przemyslaw-Wosko thanks for the info! Since Xcode 9.2 comes with Swift 4.0.3 adding a new Sourcery binary compiled with Swift 4.0.3 would solve the problem.

**Comment by pgorzelany** [comment]
@Przemyslaw-Wosko Changing Podfile.lock to update Sourcery to the latest version solved the problem. I think it should also be updated in SwiftyMocky so the latest version of Sourcery is installed automatically.

**Comment by Przemyslaw-Wosko** [comment]
@pgorzelany 
Glad to hear that, if you are interested in development or seek help with SwiftyMocky, join our Slack channel. 

Regarding Sourcery versioning - good idea :)

**Comment by Rameshwar-Gade** [comment]
Facing the same issue on Xcode 9.1 as well.

**Comment by beretis** [comment]
I'm having the same issue `error: /var/folders/j0/qlw1rfwd6fd_nqzvq_m0v9_80000gn/T/SwiftTemplate.build/main.swift:2:8: error: module compiled with Swift 4.0.3 cannot be imported in Swift 4.1: /var/folders/j0/qlw1rfwd6fd_nqzvq_m0v9_80000gn/T/SourceryRuntime.framework/Modules/SourceryRuntime.swiftmodule/x86_64.swiftmodule
import SourceryRuntime`

**Comment by amichnia** [comment]
A general solution, for now, is to use "get_sourcery" script, (manually or as a post install script), and get prebuilt Sourcery binaries. 

We will look into versioning issues in more detail, but for now I think we can consider this issue closed.
