### ISSUE TITLE
error: Compile Swift Module 'SourceryRuntime' (27 sources)

### ISSUE THREAD

**Issue by maciej-gad-benefex** [MakeAWishFoundation/SwiftyMocky#177]
It looks like a new `Sourcery` version (0.16) has breaking changes. After updating `SwiftyMocky` and `Sourcery` to the newest versions using this CocoaPods call:

```
pod update
```

and trying to use `SwiftyMocky`:

```
Pods/Sourcery/bin/sourcery --config mocky.yml
```

I've got this error message:
```
Using configuration file at 'mocky.yml'
Scanning sources...
Found 695 types.
Loading templates...
Loaded 1 templates.
Generating code...
error: Compile Swift Module 'SourceryRuntime' (27 sources)
Compile Swift Module 'SwiftTemplate' (1 sources)
/private/var/folders/8w/gplgg1_d67z09nwt9y7l78xw0000gp/T/SwiftTemplate/0.16.0/Sources/SwiftTemplate/main.swift:48:29: error: use of unresolved identifier 'arguments'; did you mean 'argument'?
 for rule in swiftLintRules(arguments) {
                            ^~~~~~~~~
                            argument
/private/var/folders/8w/gplgg1_d67z09nwt9y7l78xw0000gp/T/SwiftTemplate/0.16.0/Sources/SwiftTemplate/main.swift:7:5: note: 'argument' declared here
let argument = context.argument
    ^
/private/var/folders/8w/gplgg1_d67z09nwt9y7l78xw0000gp/T/SwiftTemplate/0.16.0/Sources/SwiftTemplate/main.swift:52:27: error: use of unresolved identifier 'arguments'; did you mean 'argument'?
 if let swiftyMockyArgs = arguments["swiftyMocky"] as? [String: Any], let rules = swiftyMockyArgs["excludedSwiftLintRules"] as? [String] {
                          ^~~~~~~~~
                          argument
/private/var/folders/8w/gplgg1_d67z09nwt9y7l78xw0000gp/T/SwiftTemplate/0.16.0/Sources/SwiftTemplate/main.swift:7:5: note: 'argument' declared here
let argument = context.argument
    ^
/private/var/folders/8w/gplgg1_d67z09nwt9y7l78xw0000gp/T/SwiftTemplate/0.16.0/Sources/SwiftTemplate/main.swift:60:38: error: use of unresolved identifier 'arguments'; did you mean 'argument'?
 for projectImport in projectImports(arguments) {
                                     ^~~~~~~~~
                                     argument
/private/var/folders/8w/gplgg1_d67z09nwt9y7l78xw0000gp/T/SwiftTemplate/0.16.0/Sources/SwiftTemplate/main.swift:7:5: note: 'argument' declared here
let argument = context.argument
    ^
/private/var/folders/8w/gplgg1_d67z09nwt9y7l78xw0000gp/T/SwiftTemplate/0.16.0/Sources/SwiftTemplate/main.swift:64:27: error: use of unresolved identifier 'arguments'; did you mean 'argument'?
 if let swiftyMockyArgs = arguments["swiftyMocky"] as? [String: Any] {
                          ^~~~~~~~~
                          argument
/private/var/folders/8w/gplgg1_d67z09nwt9y7l78xw0000gp/T/SwiftTemplate/0.16.0/Sources/SwiftTemplate/main.swift:7:5: note: 'argument' declared here
let argument = context.argument
    ^
/private/var/folders/8w/gplgg1_d67z09nwt9y7l78xw0000gp/T/SwiftTemplate/0.16.0/Sources/SwiftTemplate/main.swift:71:38: error: use of unresolved identifier 'arguments'; did you mean 'argument'?
 for projectImport in projectImports(arguments) {
                                     ^~~~~~~~~
                                     argument
/private/var/folders/8w/gplgg1_d67z09nwt9y7l78xw0000gp/T/SwiftTemplate/0.16.0/Sources/SwiftTemplate/main.swift:7:5: note: 'argument' declared here
let argument = context.argument
    ^
/private/var/folders/8w/gplgg1_d67z09nwt9y7l78xw0000gp/T/SwiftTemplate/0.16.0/Sources/SwiftTemplate/main.swift:75:27: error: use of unresolved identifier 'arguments'; did you mean 'argument'?
 if let swiftyMockyArgs = arguments["swiftyMocky"] as? [String: Any] {
                          ^~~~~~~~~
                          argument
/private/var/folders/8w/gplgg1_d67z09nwt9y7l78xw0000gp/T/SwiftTemplate/0.16.0/Sources/SwiftTemplate/main.swift:7:5: note: 'argument' declared here
let argument = context.argument
```

The workaround for this issue is to downgrade `Sourcery` to `0.15.0` version. In your `Podfile` change:
```
pod 'SwiftyMocky'
```
to:
```
pod 'Sourcery', '0.15.0'
pod 'SwiftyMocky'
```
and then remove `Podfile.lock`:
```
rm Podfile.lock
```
and then install pods:
```
pod install
```
After that `Pods/Sourcery/bin/sourcery --config mocky.yml` should work fine. I know this is a temporary workaround, so it will be good to spend a little more time and fix this issue. I will try to find time to do a better fix, but any help will be appreciated. 

Cheers!

**Comment by amichnia** [comment]
@maciej-gad-benefex Thanks for raising, its on the pipeline

**Comment by amichnia** [comment]
@maciej-gad-benefex SwiftyMocky 3.2.0 is there. It solves the problem, as it works on top of Sourcery 0.16.0
